
server.port=8080
spring.application.name=ProjectS
spring.datasource.url=jdbc:postgresql://localhost:5432/Hintmatrix
spring.datasource.username=postgres
spring.datasource.password=ragava@2244
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub


jwt.secret=ProjectS_CA_Education_Portal_SpringBoot_JWT_Secret_Key_2026_ChangeMe_123456789
jwt.expiration=3600000
logging.level.org.springframework.security=DEBUG