
spring.application.name=ProjectS
spring.datasource.url=jdbc:postgresql://localhost:5432/ProjectS_DB
spring.datasource.username=postgres
spring.datasource.password=ragava@2244
spring.datasource.driver-class-name=org.postgresql.Driver
