hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/Hintmatrix
hibernate.connection.username=postgres
hibernate.connection.password=ragava@2244
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#hibernate.default_schema=public